### ISSUE TITLE
getcache has no results

### ISSUE THREAD

**Issue by 641i130** [LimeLightCards/wstcg-scraper#1]
Running the following results in nothing in the `cache/carddata` folder:
```bash
# npm run weiss:getcache

> wstcg-scraper@1.0.0 weiss:getcache
> ts-node scripts/get-cache
#
```

**Comment by seiyria** [comment]
Unfortunately I never actually got the scraper working. I wanted to use it, but ended up using Beanwolfs work instead. Would be happy to collab on getting it working, though!

**Comment by 641i130** [comment]
Oh shoot ok, thanks for letting me know!

**Comment by 641i130** [comment]
Care to link 'Beanwolf's work?

**Comment by seiyria** [comment]
Here's the repo that does it: https://github.com/LimeLightCards/cards

Here's his repo: https://github.com/CCondeluci/WeissSchwarz-ENG-DB
